### ISSUE TITLE
just want to know which font 

### ISSUE THREAD

**Issue by tangchongcf** [kyazdani42/blue-moon#5]
Can you tell me which font does the pic used please? I see it from nvim-tree, and it's the blue-moon theme,  but it want to know which font you used. I like it very much!!!

![195207043-e1829a8b-7e73-4f7a-97b2-f65dc31387ce](https://github.com/kyazdani42/blue-moon/assets/126157895/8d875818-6619-4fff-8cff-3868901e7505)

**Comment by kyazdani42** [comment]
Hi :)

the font is `Noto Sans Mono` patched with nerd fonts

**Comment by tangchongcf** [comment]
@kyazdani42  thanks!
but why the keywords in code, such as `if`, `function`, is different from `Noto Sans Mono`?
I like the oblique font very much. is it realy `Noto Sans Mono`?

**Comment by kyazdani42** [comment]
I'd prefer noto sans mono for italics, but since italics for this font are not supported on linux i have to set a different one.
The one you see on this picture is `IBMPlex mono`, but I now use `Roboto Mono` since it's less cluttered though.
